version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react-i18next
    versions:
    - 11.8.14
  - dependency-name: "@types/node"
    versions:
    - 15.0.0
